### ISSUE TITLE
Build not possible with Visual Studio 2017

### ISSUE THREAD

**Issue by Tondorian** [EasyRPG/buildscripts#19]
It is not possible to compile the buildscript if you have only vs2017 and the vs2015 compatible compiler installed. I tried the original guide from https://github.com/EasyRPG/Player/blob/master/README.md (v140) and also (V141). If I try to compile it from VS directly I get a missing sdl_config.h error. 
[targetv140.txt](https://github.com/EasyRPG/buildscripts/files/924245/targetv140.txt)
[targetv141.txt](https://github.com/EasyRPG/buildscripts/files/924246/targetv141.txt)

**Comment by carstene1ns** [comment]
The windows toolchain needs a revamp. A lot of dependencies are outdated in the meanwhile and it seems the generator is broken, too. `SDL_config.h` should be included in the source archive and (i guess) should be copied over to some include directory by the generator.

**Comment by Ghabry** [comment]
That missing SDL_config.h is some dependency problem I wasn't able to track down yet. You can solve it by running the build again because one of the buildsteps copied that file before other parallel steps failed.

**Comment by Tondorian** [comment]
Now i get a lot of unresolved symbols. 
No project has a reference to windows/build/include or any lib directory. Maybe my VS destroyed these projects.

**Comment by Ghabry** [comment]
I also never tried to compile anything with VS2017 btw, still have VS2015, I can't fit two Visual Bloat Studios on one harddisk :(

**Comment by Tondorian** [comment]
I updated my installation because of some c# feature and now i ran into c++ issues 👎  my fault ... 
I found this tool https://github.com/Microsoft/vcpkg to manage c++ packages and compile them from source. VS2017 also supports nuget and c++ but this packages are for v140 compiler only. At least all packages i tried

**Comment by Tondorian** [comment]
Just a small update i reinstall windows and vs2017 and it does still not work so it is not happen because vs2015 was not removed completely.

**Comment by Ghabry** [comment]
Do you use the correct command line for building?
You have to pick "Visual Studio Crosstools" from the start menu or how they are called.

Some of them don't set %Platform% correctly and the build will fail.
Type "echo %Platform%" and tell me the result.

I think for x86 you must pick the "x64 x86 Crosstools" otherwise the variable is not set :/

**Comment by Tondorian** [comment]
I always use "Developer Prompt for Visual Studio 2017" 
result: "echo %Platform%
%Platform%"

after using "x86_x64 Cross Tools Command Prompt for VS 2017" 
it start compiling and after a while i get a lot of No such file or directory issues:
```
"G:\Projekte\CPP\EasyRPG\buildscripts\windows\easyrpg-win32-libs.sln" (Clean;Build Ziel) (1) ->
       "G:\Projekte\CPP\EasyRPG\buildscripts\windows\projects\freetype.vcxproj.metaproj" (Standardziel) (20:2) ->
       "G:\Projekte\CPP\EasyRPG\buildscripts\windows\projects\harfbuzz.vcxproj.metaproj" (Standardziel) (19:3) ->
       "G:\Projekte\CPP\EasyRPG\buildscripts\windows\projects\harfbuzz.vcxproj" (Standardziel) (26:3) ->
         g:\projekte\cpp\easyrpg\buildscripts\windows\projects\harfbuzz-1.3.2\src\hb-ft.h(34): fatal error C1083: Datei
        (Include) kann nicht geöffnet werden: "ft2build.h": No such file or directory [G:\Projekte\CPP\EasyRPG\buildscr
       ipts\windows\projects\harfbuzz.vcxproj]
         g:\projekte\cpp\easyrpg\buildscripts\windows\projects\harfbuzz-1.3.2\src\hb-icu.h(34): fatal error C1083: Date
       i (Include) kann nicht geöffnet werden: "unicode/uscript.h": No such file or directory [G:\Projekte\CPP\EasyRPG\
       buildscripts\windows\projects\harfbuzz.vcxproj]
```

**Comment by Ghabry** [comment]
When %Platform% echoes %Platform% it is not correctly set. Wrong command prompt used.

Could you try setting the environment variable "EASYDEV_MSVC" to the "build" folder?

Should be "G:\Projekte\CPP\EasyRPG\buildscripts\windows\build"

and logout/login again.

**Comment by Tondorian** [comment]
after setting `EASYDEV_MSVC` it starts to compile :) thank you so it is a pre compile step or is it a bug with vs2017?

**Comment by Ghabry** [comment]
Sounds like a bug in the buildscript. The buildscript should set EASYDEV_MSVC when it is not set. Maybe never tested that case >.>

**Comment by Tondorian** [comment]
Now it works thank you 👍

**Comment by fmatthew5876** [comment]
I can confirm being able to build with VS2017 also using the scripts.

I also remember why I prefer developing on unix...

**Comment by Ghabry** [comment]
Fortunately vcpkg fixes most of the annoyances by providing some kind of package manager.
We haven't migrated to it yet but I already use it locally (+cmake) when building for Windows.

**Comment by Ghabry** [comment]
You can build using an unmodified ICU but you will get a gigantic library (25 MB).
For a custom datafile we need unfortunately a custom vcpkg recipe:
https://github.com/Ghabry/vcpkg/commit/9ec3fce30bd2c9906abe30cce9190d953e249c6b#diff-694f51364b8034d3b4cb907c33a34781
(recipe is probably outdated by now, not sure if it still works)

The other stuff in the commit is not needed anymore.

``vcpkg install expat freetype libpng libvorbis libsndfile wildmidi libxmp-lite pixman sdl2-mixer speexdsp opusfile icu --triplet x86-windows-static`` should get everything installed that you need.

Afterwards open the CMakeLists.txt in Visual Studio, set -DCMAKE_PREFIX_PATH and so on, I assume you know the CMake basics :). (don't use the Visual Studio generator of CMake, the find modules can't properly detect debug vs. release libraries because they have the same name, so you will get lots of linker warnings about LIBCMTD, or when using the VS Generator use -DCMAKE_BUILD_TYPE=Debug, then only the Debug build will work but you don't get linker issues ;)).
