### ISSUE TITLE
Patch pixman to use fastpaths for our ports

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/buildscripts#43]
Pixman has compile-time and runtime checks for some NEON, SSE and such optimizations.
However, the runtime check only works on supported platforms like GNU/Linux.

Solution: patch them out with some `#ifdef` to enable them for Switch, 3DS and PSVita, it should give us a speed boost.

**Comment by Ghabry** [comment]
For reference, the relevant line is here: https://github.com/aseprite/pixman/blob/master/pixman/pixman-arm.c#L184

For the terrible CPU of the 3DS this involves setting the ARM_V6 bit and for Vita and Switch ARM_NEON.

**Comment by carstene1ns** [comment]
Just a reminder that `libopus` is currently also built without them:
https://github.com/EasyRPG/buildscripts/blob/46d6d628434da2939e97477ef729946a258f5953/shared/packages.sh#L90

**Comment by Ghabry** [comment]
Performance tests on old 3DS:

On average the FPS increase by 5 FPS on empty maps. Is a bit hard to measure exactly because the FPS jump quickly (e.g. in YN you have sometimes 20-55 FPS).

With more pictures it increases more, e.g. static scenes in Witch's Heart intro reach now 55 instead of 45 FPS.

Nice speedup without any extra work on our side :)

**Comment by Ghabry** [comment]
Patch accepted upstream https://gitlab.freedesktop.org/pixman/pixman/-/merge_requests/31
